### PR TITLE
workaround infinity loop on full-screen

### PR DESCRIPTION
**Pull request by janbar**
Probably due a unknown bug in Kodi core

### CODE REVIEW

**Comment by janbar** [comment]
I resized epggrid to be not equal 1920.

**Comment by bryanbrazil** [comment]
What problem does this solve? Not sure what you mean by infinity loop.

**Comment by janbar** [comment]
I mean kodi freeze with 100% cpu when opening Guide timeline screen. Updating grid size fixes the issue.

**Comment by janbar** [comment]
Same issue with Jarvis beta-4. Any news about ?

**Comment by bryanbrazil** [comment]
I haven't been able to replicate this issue, wondering if it only happens on Linux? Don't see why grid width would affect cpu load.

**Comment by janbar** [comment]
Yes I have the issue only with Linux. Trying Windows and OSX, I haven't it. So probably it depends of the rendering framework.

**Comment by janbar** [comment]
No longer issue since kodi 17 beta

**Pull request closed without merging**
