### PR TITLE
Add Start music in fullscreen visualisation mode setting

### PR DESCRIPTION
**Pull request by brighthaven**
Hi braz96. The following code adds the option for music to launch in fullscreen visualization mode when playback starts. I have been using this code along with the Artist Slideshow set as the background with mimic (jarvis) for about a year and feel it is time to upload and share the code. (also so that when updates happen I wont have to keep re-adding it .. hehe.) 
I have submitted the changes for jarvis and now for the main branch as well.
Thanks

### CODE REVIEW

**Comment by braz96** [comment]
Tested it out, but it doesn't seem to work in every case. For example, I couldn't get it to work when starting PartyMode from the home screen or music library. It did work when starting PartyMode from the music playlist window though. Will test some more and see if it's something I would want to add.

**Comment by braz96** [comment]
I noticed that it also doesn't activate musicviz if there is already another song playing when you play a song. Don't think I'll be adding this option, would be better if Kodi implemented this so it wouldn't require a custom window.

**Comment by brighthaven** [comment]
I agree it would be better if musicviz wasn't implemented in Kodi as a window, but instead as an actual background so that it could be shown behind all transparent menus when not full screen. Unfortunately it is not.
When Party mode launches it intentionally displays the playlist that was generated.
Starting another song when one is already playing does not initiate a launch of musviz because it is already running and a "stop" was never called. 

Playing a file, folder, playlist or music stream does launch and work as expected.

**Comment by brighthaven** [comment]
I was testing out the code the other day and indeed noticed some strangeness. Turns out I missed a bracket on the custom_1135 xml. 

`!SubString(Window(videolibrary).Property(TvTunesIsAlive),True + !Skin.HasSetting.....`

should have been

`!SubString(Window(videolibrary).Property(TvTunesIsAlive),True) + !Skin.HasSetting.....`

I've uploaded the change.

Sorry about that braz96.

**Pull request closed without merging**
